# Generated by Django 4.0.4 on 2022-05-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
